# 가벼운 파이썬 공식 이미지를 사용
FROM python:3.10-slim

WORKDIR /app

# API 서버에 필요한 의존성 파일만 복사
COPY api_requirements.txt .

# 의존성 설치
RUN pip install --no-cache-dir -r api_requirements.txt

# 나머지 소스 코드 복사
COPY . .

# Uvicorn 서버 실행
CMD ["uvicorn", "application:app", "--host", "0.0.0.0", "--port", "8000"]